language: python
python:
  - "3.6"
  - "3.7"

install:
  - sudo apt-get update
  - sudo apt-get install -y libmysqlclient-dev
  - sudo pip isntall -r REQUIREMENTS.txt

sudo: required

script:
  - python -m pytest
