language: python
python:
  - "3.5"
  - "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install -y libmysqlclient-dev
  - pip install -r REQUIREMENTS.txt

sudo: required

script:
  - python -m pytest -v
